[tool.poetry]
name = "blaise-data-delivery-status"
version = "0.1.0"
description = ""
authors = ["Blaise 5 Team"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^1.1.2"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
