### Create record
POST http://localhost:5007/state/OPN2004A
Content-Type: application/x-www-form-urlencoded

state=failed yeah
created
### Update record
PATCH http://localhost:5007/state/OPN2004A
Content-Type: application/x-www-form-urlencoded

state=failed yeah

### Get Record
GET localhost:5007/state/OPN2004A

### Get Record 404
GET localhost:5007/state/OPN2007T
### Get Record